---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[nginx-site::default]
    attributes:
      vhosts:
        test:
          server_name: "test-server"
          root: "/tmp"
          default: true
          autoindex: true
