default['php']['ini']['timezone'] = 'America/Chicago'
default['php']['ini']['post_max_size'] = '8M'
default['php']['ini']['upload_max_filesize'] = '8M'
default['php']['modules'] = []
default['php']['ini']['error_reporting'] = 'E_ERROR | E_WARNING | E_PARSE'
default['php']['ini']['log_errors'] = 'on'
default['cascade']['stage'] = 'unk'
default['php']['ini']['max_input_vars'] = '8M'
default['php']['ini']['smtp'] = 'localhost'